# Generated by Django 4.2.6 on 2023-11-08 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_remove_category_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(through='news.SubscribersCategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('WE', 'мировые события'), ('PO', 'политика'), ('CU', 'культура'), ('EC', 'экономика'), ('SC', 'наука'), ('SP', 'спорт'), ('AN', 'другое')], default='AN', max_length=255, unique=True),
        ),
    ]
